[application]

[bundle]
identifier = "com.gabrielhooks"
publisher = "Gabriel Hooks"
icon = ["assets/icon.png"]

[web.app]
base_path = "imgfxdx-ghpages"

# HTML title tag content
title = "imgfxdx"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
